import type { CrmDraft } from "@/lib/crm"

// One-time import into `crm_items` when the table is first created.
// Jobs come from the old Job search tracker (tracker/jobs.json), corrected with what the
// public Ashby/Lever job boards showed on Sept 17, 2026. Salary guesses from the old
// tracker were dropped; only compensation published in the posting is kept.

const imported = (text: string) => [
  { id: "import", at: "2026-09-17T12:00:00.000Z", type: "note" as const, text },
]

const base = {
  contactName: null,
  contactRole: null,
  contactEmail: null,
  contactUrl: null,
  nextStep: null,
  nextStepDate: null,
}

export const CRM_SEED: CrmDraft[] = [
  {
    ...base,
    kind: "job",
    company: "ClickHouse",
    title: "Marketing Operations",
    url: "https://jobs.ashbyhq.com/clickhouse/8b979cad-e68c-4214-8253-bca819590447",
    location: "Remote (US)",
    compensation: "$110K – $190K + equity (posted)",
    source: "Ashby",
    stage: "lead",
    priority: 1,
    nextStep: "Read the full posting, tailor the Martech CV version, apply",
    nextStepDate: "2026-09-22",
    notes: "Marketing-ops role at a company that also lists a GTM Engineer opening. Best fit for the Senior Martech CV version. US-remote posting: check whether they hire contractors in LATAM.",
    tags: ["verified", "us-remote", "martech"],
    activities: imported("Found in the Sept 17 job-board scan (Ashby)."),
  },
  {
    ...base,
    kind: "job",
    company: "ClickHouse",
    title: "GTM Engineer, AI & Automation",
    url: "https://jobs.ashbyhq.com/clickhouse/8997dfc4-1413-4b63-9388-904e289a9a6a",
    location: "Remote (US)",
    compensation: "Not posted",
    source: "Ashby",
    stage: "lead",
    priority: 1,
    nextStep: "Close the SQL/dbt and evals gaps (Roadmap), then apply with a case study",
    notes: "Builder role inside RevOps. Asks for 5+ years of GTM automation in production, Salesforce, Gong, Clay, n8n, Vercel, Python/TypeScript, SQL + dbt, and LLM evals/observability (Langfuse). Stretch today.",
    tags: ["verified", "us-remote", "stretch"],
    activities: imported("Imported from the old tracker; verified live on Ashby on Sept 17."),
  },
  {
    ...base,
    kind: "job",
    company: "Oscilar",
    title: "Growth Engineer (founding)",
    url: "https://jobs.ashbyhq.com/oscilar/2288cde3-0012-4dc3-9ee1-6e68f997911b",
    location: "Remote (US)",
    compensation: "$176K – $210K + equity (posted)",
    source: "Ashby",
    stage: "lead",
    priority: 1,
    nextStep: "Apply, then message the Head of Growth",
    nextStepDate: "2026-09-24",
    notes: "Builds GTM data pipelines, Salesforce + enrichment integrations, BDR/AE tooling, attribution, and experiments. Asks for 5+ years of software engineering and warehouse/ETL experience — high engineering bar.",
    tags: ["verified", "us-remote"],
    activities: imported("Imported from the old tracker (listed as 'Founding Growth Engineer'); verified live on Ashby on Sept 17."),
  },
  {
    ...base,
    kind: "job",
    company: "Oscilar",
    title: "Growth Manager, Outbound",
    url: "https://jobs.ashbyhq.com/oscilar/f66f24ff-495b-400a-af28-c902cd8a20a1",
    location: "Remote",
    compensation: "$155K – $184K + equity (posted)",
    source: "Ashby",
    stage: "lead",
    priority: 2,
    notes: "Outbound-focused growth role. Check requirements and location eligibility.",
    tags: ["verified", "remote"],
    activities: imported("Found in the Sept 17 job-board scan (Ashby)."),
  },
  {
    ...base,
    kind: "job",
    company: "Oscilar",
    title: "Growth Manager, International (LATAM & EMEA)",
    url: "https://jobs.ashbyhq.com/oscilar/2012b91b-055d-457e-9407-a8c2089fb0a2",
    location: "Remote",
    compensation: "$195K – $225K + equity (posted)",
    source: "Ashby",
    stage: "lead",
    priority: 2,
    notes: "LATAM market focus — native Spanish and being based in Colombia could be an edge. Probably expects fintech/B2B growth leadership; check requirements.",
    tags: ["verified", "remote", "latam"],
    activities: imported("Found in the Sept 17 job-board scan (Ashby)."),
  },
  {
    ...base,
    kind: "job",
    company: "Level AI",
    title: "Revenue Operations Architect — GTM Systems Builder",
    url: "https://jobs.ashbyhq.com/level-ai/ba2b8d96-a353-4cbe-a3ef-0cb749781dcd",
    location: "Remote (US)",
    compensation: "Not posted",
    source: "Ashby",
    stage: "lead",
    priority: 3,
    notes: "Reports to the CRO. Mostly forecasting, deal desk, CPQ and territories (not your lane), plus GTM agents. Asks for 6+ years of RevOps at $20M–$100M ARR SaaS.",
    tags: ["verified", "us-remote", "low-fit"],
    activities: imported("Imported from the old tracker; verified live on Ashby on Sept 17."),
  },
  {
    ...base,
    kind: "job",
    company: "Assembly",
    title: "Growth & GTM Engineer",
    url: "https://jobs.ashbyhq.com/assembly/02a10ccf-18d1-4141-8f31-846da65804cb",
    location: "New York (in person)",
    compensation: "$139K – $180K + equity (posted)",
    source: "Ashby",
    stage: "lead",
    priority: 3,
    notes: "Strong skills fit (Clay, outbound automation, onboarding flows, A/B tests; reports to the CEO) but the posting requires working in person in NYC.",
    tags: ["verified", "on-site"],
    activities: imported("Imported from the old tracker (it said remote); the Ashby posting says in-person NYC."),
  },
  {
    ...base,
    kind: "job",
    company: "Netic",
    title: "GTM Engineer",
    url: "https://jobs.ashbyhq.com/netic/91731d28-28f2-4c35-a8de-ee382b0721d4",
    location: "San Francisco (on-site)",
    compensation: "Not posted",
    source: "Ashby",
    stage: "lead",
    priority: 3,
    notes: "On-site in San Francisco according to the posting.",
    tags: ["verified", "on-site"],
    activities: imported("Imported from the old tracker (it said remote); the Ashby posting says San Francisco."),
  },
  {
    ...base,
    kind: "job",
    company: "Dust",
    title: "Growth Engineer",
    url: "https://jobs.ashbyhq.com/dust/18f24ccf-5182-4099-8802-ab9b36e88db7",
    location: "San Francisco (on-site)",
    compensation: "$100K – $200K (posted)",
    source: "Ashby",
    stage: "lead",
    priority: 3,
    notes: "On-site in San Francisco according to the posting.",
    tags: ["verified", "on-site"],
    activities: imported("Imported from the old tracker (it said remote); the Ashby posting says San Francisco."),
  },
  {
    ...base,
    kind: "job",
    company: "Maven AGI",
    title: "Senior GTM Growth Engineer",
    url: "https://jobs.ashbyhq.com/mavenagi",
    location: "Unknown",
    compensation: null,
    source: "Old tracker",
    stage: "lead",
    priority: 3,
    notes: "Could not verify: the Ashby board returned 404 on Sept 17. Check their careers page before spending time on it.",
    tags: ["unverified"],
    activities: imported("Imported from the old tracker; not found on Sept 17."),
  },
  {
    ...base,
    kind: "job",
    company: "Nightfall AI",
    title: "Director, Revenue Operations & GTM Engineer",
    url: "https://www.linkedin.com/jobs/view/4461539514",
    location: "Remote (US)",
    compensation: null,
    source: "LinkedIn",
    stage: "lead",
    priority: 3,
    notes: "Could not verify: the Lever board returned 404 on Sept 17. Director-level RevOps — confirm it's still open.",
    tags: ["unverified"],
    activities: imported("Imported from the old tracker; not found on Sept 17."),
  },
  {
    ...base,
    kind: "job",
    company: "Sentra",
    title: "GTM Engineer",
    url: "https://www.linkedin.com/jobs/view/4456960197",
    location: "New York / Remote",
    compensation: null,
    source: "LinkedIn",
    stage: "lead",
    priority: 3,
    notes: "Could not verify: the Lever board returned 404 on Sept 17.",
    tags: ["unverified"],
    activities: imported("Imported from the old tracker; not found on Sept 17."),
  },
  {
    ...base,
    kind: "job",
    company: "Ease Health",
    title: "GTM Engineer",
    url: "https://www.linkedin.com/jobs/view/4466011855",
    location: "New York",
    compensation: null,
    source: "LinkedIn",
    stage: "lead",
    priority: 3,
    notes: "Not verified yet. Check location requirements.",
    tags: ["unverified"],
    activities: imported("Imported from the old tracker."),
  },
  {
    ...base,
    kind: "job",
    company: "Unknown (via Jobgether)",
    title: "GTM Engineer",
    url: "https://www.linkedin.com/jobs/view/4465778384/",
    location: "United States",
    compensation: null,
    source: "LinkedIn (aggregator)",
    stage: "lead",
    priority: 3,
    notes: "Aggregator listing that hides the real employer. Low priority.",
    tags: ["unverified", "aggregator"],
    activities: imported("Imported from the old tracker."),
  },
  {
    ...base,
    kind: "client",
    company: "Building Intelligence",
    title: "Testimonial + referrals",
    url: null,
    location: "New York",
    compensation: null,
    source: "Existing client",
    stage: "lead",
    priority: 1,
    nextStep: "Ask for a short testimonial for the services page and intros to other funded startups",
    nextStepDate: "2026-09-25",
    notes: "Client for the Clay + Apollo + Salesforce outbound funnels. Also ask for the numbers behind that work for the case study.",
    tags: ["referral", "testimonial"],
    activities: imported("Added from the job search plan (testimonials)."),
  },
  {
    ...base,
    kind: "client",
    company: "Pvragon",
    title: "Testimonial + subcontract work",
    url: null,
    location: null,
    compensation: null,
    source: "Former employer",
    stage: "lead",
    priority: 2,
    nextStep: "Ask for a testimonial and whether they subcontract GTM builds",
    nextStepDate: "2026-09-26",
    notes: "GTM agency for venture-backed startups where you ran the martech stack (Apr 2025 – Mar 2026).",
    tags: ["referral", "testimonial"],
    activities: imported("Added from the job search plan (testimonials)."),
  },
]
